import pandas as pd
import matplotlib.pyplot as plt

movies = pd.read_csv('movies.csv')
directors = pd.read_csv('directors.csv')    

movies = movies.drop(columns="Unnamed: 0")
directors = directors.drop(columns="Unnamed: 0")
df = pd.merge(movies, directors, left_on='director_id', right_on='id', how='inner')
# print(merged_df.head())


# task :2 avg movies rating by director 

# avg_movies_rating = df.groupby('director_name')['vote_average'].mean().sort_values(ascending=False)
# print(avg_movies_rating)

# task 3 : total revenue generated by each director

# total_revenue_by_director = df.groupby('director_name')['revenue'].sum().sort_values(ascending=False)
# print(total_revenue_by_director)

# ---------==----------------------------------------------------

# task 4 : Average Budget vs Average Revenue (Director-wise)

# avg_budget_revenue = df.groupby('director_name').agg({'budget': 'mean', 'revenue': 'mean'})
# print(avg_budget_revenue)

# task 5 : Year-wise Movie Count

# yearly_movie_count = df.groupby('year').size()
# print(yearly_movie_count)

# task 6 :Gender-wise Director Analysis Number of Movies by Gender.

# gender_movie_count = df.groupby('gender')['director_name'].nunique()
# print(gender_movie_count) 

# task 7 : Best Director per Year (Highest Revenue)
# best_director_per_year = df.groupby('year')[['director_name', 'revenue']].max()
# print(best_director_per_year)

# task 8 : Director with Most Big-Budget Movies(Budget > 50 million)

# big_budget_movies = df[df['budget'] > 50000000]
# director_big_budget_count = big_budget_movies['director_name'].count()
# print(director_big_budget_count)

# which gender has higher / lower rating . 

# gender_rating = df.groupby('gender')['vote_average'].mean()
# plt.boxplot(gender_rating)
# plt.title('Movie Ratings by Director Gender')
# plt.ylabel('Vote Average')  
# plt.show/()


# task  :1 Multiple Line Graph: Budget, Revenue & Profit
# profit = budget - revenue

# df['profit'] = df['revenue'] - df['budget']
# year_finance = df.groupby('year')[['budget', 'revenue', 'profit']].mean()
# plt.plot(year_finance.index, year_finance['budget'], color='blue')
# plt.plot(year_finance.index, year_finance['profit'], color='green')
# plt.plot(year_finance.index, year_finance['revenue'], color='red')

# plt.xlabel('Year')
# plt.ylabel('Amount')
# plt.title('Budget, Revenue & Profit over Years')
# plt.legend(['Budget', 'Profit', 'Revenue'])
# plt.show()

# task :2 
# Multiple Line Graph: Year vs Rating & Revenue

# rating = df.groupby('year')[['vote_average', 'revenue']].mean()
# plt.plot(rating.index, rating['vote_average'], color='blue')
# plt.plot(rating.index, rating['revenue'], color='red')
# plt.xlabel('Year')
# plt.ylabel('Amount / Rating')
# plt.title('Year vs Rating & Revenue')
# plt.legend(['Vote Average', 'Revenue'])
# plt.show()


# task :3 
# Multiple Line Graph: Year vs Popularity

# year_g = df.groupby('year')['popularity'].mean()
# plt.plot(year_g.index, year_g, color='purple')
# plt.xlabel('Year')
# plt.ylabel('Popularity')
# plt.title('Year vs Popularity')
# plt.legend(['Popularity'])
# plt.show()